services:
  postgresql:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  django:
    build: ./django
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail http://localhost:8000/ || exit 1"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 5
    restart: on-failure

  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    depends_on:
      django:
        condition: service_healthy
    restart: on-failure

volumes:
  postgresql_volume:
  static_volume:
  media_volume:
